### ISSUE TITLE
Paper suggestion

### ISSUE THREAD

**Issue by minghao-wu** [SinclairCoder/Instruction-Tuning-Papers#2]
Thank you for your efforts in maintaining such a comprehensive list of papers.

Could you please add [LaMini-LM: A Diverse Herd of Distilled Models from Large-Scale Instructions](https://arxiv.org/abs/2304.14402) to the list?

Thank you very much.

**Comment by SinclairCoder** [comment]
I am sorry for the late reply. your work is impressive and I have added this paper to the list. Thanks for your contribution to this repo.

**Comment by minghao-wu** [comment]
I noticed your update so I have this issue closed. Thank you as well for maintaining such a nice paper list.

**Comment by SinclairCoder** [comment]
😁
